package dev.csvdiff;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.List;
import java.util.Map;

/**
 * The result contract: what an engine returns and what every sink consumes.
 *
 * <p>This is the API. {@code ReportRenderer}, the CLI's JSON sidecar and the CI summaries read
 * only these types, and the JSON shape is byte-compatible with the Python and TypeScript
 * implementations of csvdiff, so a report generated by any of the three is interchangeable. Add a
 * field rather than reshaping an existing one.
 *
 * <p>A CSV cell is a {@code String} that may be {@code null}: values are read as text with no type
 * inference, and an empty field — quoted or not — is absent rather than a zero-length string.
 */
public final class Contract {

  private Contract() {}

  /** Row counts. Always exact, even when the embedded row lists are capped. */
  @JsonPropertyOrder({
    "a_rows", "b_rows", "a_keys", "b_keys", "matched", "unchanged", "changed", "added", "removed",
    "a_dup_keys", "a_dup_rows", "b_dup_keys", "b_dup_rows"
  })
  public record Counts(
      @JsonProperty("a_rows") long aRows,
      @JsonProperty("b_rows") long bRows,
      @JsonProperty("a_keys") long aKeys,
      @JsonProperty("b_keys") long bKeys,
      @JsonProperty("matched") long matched,
      @JsonProperty("unchanged") long unchanged,
      @JsonProperty("changed") long changed,
      @JsonProperty("added") long added,
      @JsonProperty("removed") long removed,
      @JsonProperty("a_dup_keys") long aDupKeys,
      @JsonProperty("a_dup_rows") long aDupRows,
      @JsonProperty("b_dup_keys") long bDupKeys,
      @JsonProperty("b_dup_rows") long bDupRows) {

    /** The count for a row status, used where the status is only known at runtime. */
    public long forStatus(String status) {
      return switch (status) {
        case "added" -> added;
        case "removed" -> removed;
        case "changed" -> changed;
        case "matched" -> matched;
        case "unchanged" -> unchanged;
        default -> throw new IllegalArgumentException("Unknown status: " + status);
      };
    }
  }

  /** How one compared column fared across the matched rows. */
  public record ColumnStat(
      @JsonProperty("name") String name,
      @JsonProperty("changed") long changed,
      @JsonProperty("blanked") long blanked,
      @JsonProperty("filled") long filled) {}

  /**
   * One differing cell of a changed row, serialised as the array {@code [columnIndex, a, b]}.
   * Changed rows carry these triples rather than whole rows; keeping the payload sparse is what
   * keeps a report with tens of thousands of changes near a megabyte.
   *
   * @param column index into {@code meta.compared}
   */
  @JsonFormat(shape = JsonFormat.Shape.ARRAY)
  @JsonPropertyOrder({"column", "a", "b"})
  public record CellDiff(
      @JsonProperty("column") int column,
      @JsonProperty("a") String a,
      @JsonProperty("b") String b) {}

  /**
   * A capped list of rows plus the header for them.
   *
   * @param rows for added/removed/duplicates a list of cell values; for changed rows the key values
   *     followed by a {@code List<CellDiff>}
   * @param truncated whether the full list is longer than {@code rows}
   */
  public record Section(
      @JsonProperty("cols") List<String> cols,
      @JsonProperty("rows") List<List<Object>> rows,
      @JsonProperty("truncated") boolean truncated) {}

  /** One of the two compared files. */
  public record FileMeta(
      @JsonProperty("name") String name,
      @JsonProperty("path") String path,
      @JsonProperty("size") long size) {}

  /** What the engine resolved before comparing: the key, the compared columns, the schema drift. */
  public record EngineMeta(
      @JsonProperty("key") List<String> key,
      @JsonProperty("compared") List<String> compared,
      @JsonProperty("only_in_a") List<String> onlyInA,
      @JsonProperty("only_in_b") List<String> onlyInB,
      @JsonProperty("a_cols") int aCols,
      @JsonProperty("b_cols") int bCols) {}

  /** {@link EngineMeta} completed with the run's own facts. */
  @JsonPropertyOrder({
    "key", "compared", "only_in_a", "only_in_b", "a_cols", "b_cols",
    "a", "b", "engine", "seconds", "generated", "options"
  })
  public record Meta(
      @JsonProperty("key") List<String> key,
      @JsonProperty("compared") List<String> compared,
      @JsonProperty("only_in_a") List<String> onlyInA,
      @JsonProperty("only_in_b") List<String> onlyInB,
      @JsonProperty("a_cols") int aCols,
      @JsonProperty("b_cols") int bCols,
      @JsonProperty("a") FileMeta a,
      @JsonProperty("b") FileMeta b,
      @JsonProperty("engine") String engine,
      @JsonProperty("seconds") double seconds,
      @JsonProperty("generated") String generated,
      @JsonProperty("options") Options options) {}

  /** What an engine produces, before the run's own facts are attached. */
  public record EngineResult(
      EngineMeta meta,
      Counts counts,
      List<ColumnStat> columns,
      Section changed,
      Section added,
      Section removed,
      Section dupA,
      Section dupB) {}

  /** A finished comparison: {@link EngineResult} with its {@link Meta} completed. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonPropertyOrder({"meta", "counts", "columns", "changed", "added", "removed", "dup_a", "dup_b"})
  public record CompareResult(
      @JsonProperty("meta") Meta meta,
      @JsonProperty("counts") Counts counts,
      @JsonProperty("columns") List<ColumnStat> columns,
      @JsonProperty("changed") Section changed,
      @JsonProperty("added") Section added,
      @JsonProperty("removed") Section removed,
      @JsonProperty("dup_a") Section dupA,
      @JsonProperty("dup_b") Section dupB) {

    /** True when the two files carry the same data under the options given. */
    public boolean identical() {
      return counts.changed() == 0 && counts.added() == 0 && counts.removed() == 0;
    }

    /** The subset written by {@code --json}: everything except the embedded row lists. */
    public Map<String, Object> summary() {
      return Map.of("meta", meta, "counts", counts, "columns", columns);
    }
  }
}
